apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maloja-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: maloja-secret
    template:
      data:
        MALOJA_FORCE_PASSWORD: "{{ `{{ .adminPassword }}` }}"
  data:
    - secretKey: adminPassword
      remoteRef:
        key: "MALOJA_ADMIN_PASSWORD"
