app-template:
  controllers:
    main:
      replicas: 1
      type: statefulset
      containers:
        main:
          image:
            repository: ghcr.io/foxxmd/multi-scrobbler
            tag: 0.11.5
          env:
            TZ: Europe/Ljubljana
            BASE_URL: https://multi-scrobbler.mfin.app
            KOITO_USER: mfin
            KOITO_URL: http://koito.koito:4110
            LASTFM_REDIRECT_URI: https://multi-scrobbler.mfin.app/lastfm/callback
            LZENDPOINT_ENABLE: "true"
          envFrom:
            - secretRef:
                name: multi-scrobbler-secret
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
              spec:
                failureThreshold: 30
                periodSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 1000Mi
      pod:
        annotations:
          reloader.stakater.com/auto: "true"
  service:
    main:
      ports:
        http:
          port: 9078
  route:
    main:
      hostnames:
        - multi-scrobbler.mfin.app
      parentRefs:
        - name: envoy-internal
          namespace: envoy-gateway
  persistence:
    config:
      enabled: true
      existingClaim: multi-scrobbler
