apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: multi-scrobbler-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: multi-scrobbler-secret
    template:
      data:
        LZE_TOKEN: "{{ `{{ .lzeToken }}` }}"
        KOITO_TOKEN: "{{ `{{ .koitoToken }}` }}"
        LASTFM_API_KEY: "{{ `{{ .lastfmApiKey }}` }}"
        LASTFM_SECRET: "{{ `{{ .lastfmSecret }}` }}"
        MB_CONTACT: "{{ `{{ .mbContact }}` }}"
  data:
    - secretKey: lzeToken
      remoteRef:
        key: "LZE_TOKEN"
    - secretKey: lastfmApiKey
      remoteRef:
        key: "LASTFM_API_KEY"
    - secretKey: lastfmSecret
      remoteRef:
        key: "LASTFM_SECRET"
    - secretKey: koitoToken
      remoteRef:
        key: "KOITO_TOKEN"
    - secretKey: mbContact
      remoteRef:
        key: "MB_CONTACT"
