apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: multi-scrobbler-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: multi-scrobbler-secret
    template:
      data:
        SUBSONIC_USER: "{{ `{{ .navidromeUser }}` }}"
        SUBSONIC_PASSWORD: "{{ `{{ .navidromePassword }}` }}"
        KOITO_TOKEN: "{{ `{{ .koitoToken }}` }}"
        MALOJA_API_KEY: "{{ `{{ .malojaApiKey }}` }}"
        LASTFM_API_KEY: "{{ `{{ .lastfmApiKey }}` }}"
        LASTFM_SECRET: "{{ `{{ .lastfmSecret }}` }}"
  data:
    - secretKey: navidromeUser
      remoteRef:
        key: "NAVIDROME_USER"
    - secretKey: navidromePassword
      remoteRef:
        key: "NAVIDROME_PASSWORD"
    - secretKey: malojaApiKey
      remoteRef:
        key: "MALOJA_API_KEY"
    - secretKey: lastfmApiKey
      remoteRef:
        key: "LASTFM_API_KEY"
    - secretKey: lastfmSecret
      remoteRef:
        key: "LASTFM_SECRET"
    - secretKey: koitoToken
      remoteRef:
        key: "KOITO_TOKEN"
