apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: koito-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: koito-secret
    template:
      data:
        KOITO_DEFAULT_PASSWORD: "{{ `{{ .password }}` }}"
        KOITO_DATABASE_URL: "{{ `{{ .postgresUrl }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: "KOITO_PASSWORD"
    - secretKey: postgresUrl
      remoteRef:
        key: "KOITO_DATABASE_URL"
