volsync:
    repository: ENC[AES256_GCM,data:MBo4Fq1ifJIrMWkhA8+vvUhH6EjHufhGdchf8T3Ugevv5NV2WRYz6H9dI5A=,iv:YahDm4gsf23c0ReS1FbJJ2/xpoiuchx4PmgiYVf6u6U=,tag:9aPuNhkNltq9kTczjn9TMw==,type:str]
    password: ENC[AES256_GCM,data:iSp+bUCfgtp+mbjdkFYWFOraZolSVX1nEKomPdhQa6o=,iv:Nnt+uPhYxsI21YMWf8mAJ6vBzFGlgyD9oQqTlqEArq8=,tag:buB2laKzmPYPDyiiYtJRlA==,type:str]
    accessKey: ENC[AES256_GCM,data:vv2fgzmzdPy8GmA6dsrV5g==,iv:+h2CYzlK+/HJPnR2WA3VtO/99lCIDKnevyC5LaMjd8E=,tag:0th6WHoFzCDN63WVdaYY4Q==,type:str]
    secretKey: ENC[AES256_GCM,data:hGY+aWVjrUhCA4y0GEiu6Z7rJgHQJj48ZC/RG+LgFTA=,iv:GXKli9mtnXGlCtMmzVOJUoColDHK+dYNfhyrAtC+Ki8=,tag:a5MEYBNA/RTLM2fJLH98qA==,type:str]
grafana:
    env:
        GF_AUTH_GENERIC_OAUTH_API_URL: ENC[AES256_GCM,data:8lZPuA2bvFEdbQ1n+l1sjMV4JSwKDR2lovCtQ50ytmHu3XHMPFQFJlQ=,iv:zksfqmhSNVR10p8VJ5lAcGFV70Fql4nNVnP/0iistHo=,tag:SP5BoJ93YSGJiZIgZj3aTw==,type:str]
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: ENC[AES256_GCM,data:UXdtcjA9NCWtln9NhgJQNtyYdX/AZvMwXlrIneJ5iuRA,iv:HERA9UKXLclqjfRbZUhrFJlEvscgisfp3H8D2FRAEt8=,tag:DIWfqTGWFOJCvjHNEGTvfQ==,type:str]
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:B05zhQy1heWzG8+kMAiYdHWs52wqUBBcIzBB8oSUUuJ7yChS1o8=,iv:LNfJmeTGTHChSgZxHtAPEWn7trPu6Skbcmr06H7iROM=,tag:uiZCHFgaBzNRZCcUVsqdXg==,type:str]
        GF_SERVER_ROOT_URL: ENC[AES256_GCM,data:gF8I/nfbXg2BBGAoh/URdx3+q3qMuZUq,iv:kCm++syNl9o2v7OCX3h1hq2ydRr8ELpfdadhp0c7zEI=,tag:HFxgrLhUj8QLszTQ0BVrzA==,type:str]
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8JU7+n1k9jw6WD5oNDxnQowNdcCR2LAloTD42/hgd1U=,iv:dbA1ae5F3/CtWVrLFQ7zMGNGiFfV5Sqli1j/abq1yts=,tag:mw2lIYYgLrWzziVvlbICWQ==,type:str]
    grafana.ini:
        auth:
            signout_redirect_url: ENC[AES256_GCM,data:1065du1aIziudT+LFMDMrCfhxVWJD80IAwlLCATv,iv:tvC+KbV2DDYWh8HrdpRGrDMp38ARFQ4yefGjUN5KZ8E=,tag:Jbnu4s2dQLFSMy8FpYvbqg==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYkFkMGVQdlJ4VmsvWEVp
            ems3SXkydmJyaG10Z3lDQVc2cm1rWUJKMUFRCnM2cXBSem9UUEVQN3d0VkdYQmRM
            Uldob3M0Q3dLUDg4WVNuMDFRaHIrTEEKLS0tIFEyMlRyTzRyTWpHRWtPZmkxaU9s
            T0RSOHlaa2ZNOVczTjlZVWRGbkc0ZjAKlyINTXqw+NA51TJ8m8xIdcNxxUFS8avq
            +fEsuPZWUhzbRWMePJeYHLXbjVIRr1JxZ8y49j1seKNpqGHSo+Dkiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T06:09:59Z"
    mac: ENC[AES256_GCM,data:kbtNE5daqIRclu/mbLNdQ4+xXkbBhrDZfSbOT7eRJGGPBy1/lQ+GgJV4zVDtSIzWqYgtb9OhisN1lJZdnmOfQSckt+YtFn9DTBRWa7YTTmowaYDMUn2VaWeNBGOMuENCqDbUF3STDi7Uk3SskSt50yezI0JElppcnBQmVedHIYQ=,iv:+plHeILJbAOER8LxSrkRV7oCbH0pWodLsrCjN7j5H50=,tag:vkevdtABP8iqD2tFYeiUiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
