default:
    domain: ENC[AES256_GCM,data:RCrpJHq3v9U=,iv:O8Z9ykx1dHaPcFfoB1Mk33beb86npTZXir/NLnSlqSE=,tag:ROqORo0jlPqQlCHvFJ/vXg==,type:str]
    nasIp: ENC[AES256_GCM,data:0eLda51rpUuMFA==,iv:IRXHYueQ8i3jXHQThB4mPgcxjgGCzWeXnvhXifM2IXw=,tag:Ktj4OgQ4ZI1o5Mbim1v1Cw==,type:str]
kube-prometheus-stack:
    prometheus: null
    alertmanager:
        config:
            receivers:
                - name: ENC[AES256_GCM,data:BRgw5SIwQaw=,iv:FfKnpmPoTlbP0yblR9SsdJiI10qJ58utpDslCDrhbBk=,tag:xlBqPJxiSZxjMUVaJDBxlQ==,type:str]
                  pushover_configs:
                    - user_key: ENC[AES256_GCM,data:vWPqgcf9/MvJ6YCmbDq8gHoaJQYdsqwhFS4roCQt,iv:k837it/sh7D81pD4FwZEjnayJvZbK/Khl+NTfk+VVzc=,tag:gfT0oSzMgX5kVxcziFqnbQ==,type:str]
                      token: ENC[AES256_GCM,data:xAk9w2sgfjk4nJjStJUinXsByJTKu3fQkCOvrPWY,iv:UXQHSLKyTDT/O360b4tWsL6kFN9tsIBDioQTRqev/oA=,tag:ObY2EFrTma65MZgBv0hPmA==,type:str]
                - name: ENC[AES256_GCM,data:uUBQIcdIOUFfHCUsINo=,iv:SNU3dvV0m0Uotk/WheCT8ByDOtLY+oL9P7FE3of64HQ=,tag:nS1DiRK7vKaOQUhPpKIqxw==,type:str]
                  webhook_configs:
                    - url: ENC[AES256_GCM,data:G6vNWLW9A9Gi+mTk3+i8ZhLmwrJ2LWDfqfKijO8zGP4U+U15QwqIIhmoQ4H+IArKTjbb8c/ecY8=,iv:iVQo6tuckuql/1AVsTotupepLwIZf1cP3TH+zO9XYD8=,tag:triqZKh7ptcBfOk6VsPvrQ==,type:str]
                      send_resolved: ENC[AES256_GCM,data:udpgzOM=,iv:ulIgPd+SKKIADeVmpZm48rQKkjcg9NLlw9uID1ugR4s=,tag:QuMjU/pU9REDsPFMOdohDA==,type:bool]
                - name: ENC[AES256_GCM,data:uB3cmw==,iv:0GbyKJx2LHXSOCTOydnXWDcemA5ZBCS60AK3K5aNYN4=,tag:N3zfyMhij4yGGuiViZuwgQ==,type:str]
    kubeControllerManager:
        endpoints:
            - ENC[AES256_GCM,data:4YFM5M1wDaXQ1w==,iv:rHiuUPFoW9rxshWFKIEuDo1Ga+KgtQLLcHs3YCkLIkA=,tag:QcXUvTkYO02Ai2ItsWCLlw==,type:str]
    kubeScheduler:
        endpoints:
            - ENC[AES256_GCM,data:KIbPL3sDl4SYvA==,iv:CqrXVT27i8MwR9rnISdPJy7bWeTpWH60TxTIYGSAfww=,tag:Rho1qmkuhJ0P328pN/O1Vw==,type:str]
    kubeProxy:
        endpoints:
            - ENC[AES256_GCM,data:z1Lgsx/bgBriUQ==,iv:e4CGXwu3tlatwfV6BGCJub+aPhKlu2UhLQxoJKqRc68=,tag:XFs8W/E1ND68ALVxD7KEpA==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4a0ErYVVkMUpPNEFYUEdm
            bWJjamZkbnpaUThNQ0NYQjF2WlRyeUpGb1RnCmlEMlJUTzdUVjNON1dobXdUQ1NY
            cHlSUWhMK0NFNzVlalRxZGVwQmtocjAKLS0tIGtONlRWODZPblJvLzVFWW5PMXlM
            cW1NK0duNStVNUw0TmRLRTFZZjJVRlkK4s2F53xRgoQbs3bZC4pb74v4bn4/aCeA
            PFE+NV03Dv37MK/BvgD5N32JHi0DfZPzdzR91MjuOaplN60Fiq5LQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T09:59:14Z"
    mac: ENC[AES256_GCM,data:0wCkhgtZY4xWcvPPXbVnF/0dQYTQXAFPhzArAEPuX5JE8BvxSAHnN42WOuvycQmputs1timhozRuEc/YMc47MhJI2wGoBEDkOWwDG5IeD0o7jOdysKrW28ZJAvk+j9zZYEV3tKp+h+hbxb74mLWhY7iBNuKuszYT/NkCxgSe+aA=,iv:Jek5KPgKTcnQAuEsJ/Fd8J3drkexpnX377qr7CkqBrw=,tag:3TYoICr4pQCitLaPEBtidA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
