app-template:
  controllers:
    main:
      replicas: 1
      type: statefulset
      containers:
        main:
          image:
            repository: ghcr.io/seerr-team/seerr
            tag: v3.3.0@sha256:c92d2dc117f62185e7bcb88cd56efd374ea79210eaf433275449e8d5988eb5a8
          env:
            TZ: Europe/Ljubljana
            PORT: &port 80
            LOG_LEVEL: info
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 1000Mi
      pod:
        securityContext:
          runAsUser: 1028
          runAsGroup: 100
          fsGroup: 100
          fsGroupChangePolicy: "OnRootMismatch"
  service:
    main:
      ports:
        http:
          port: *port
  route:
    main:
      annotations:
        external.mfin.app/managed: "true"
      hostnames:
        - dnevna.com
      parentRefs:
        - name: envoy-media
          namespace: envoy-gateway
  persistence:
    config:
      enabled: true
      existingClaim: seerr
      globalMounts:
        - path: /app/config
