app-template:
  controllers:
    main:
      replicas: 1
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            repository: ghcr.io/home-operations/qbittorrent-libtorrentv1
            tag: 5.1.4@sha256:fc48ae3a5b3daa2e80811207f659d0349da459f086faa06810f5353050da541b
          env:
            TZ: Europe/Ljubljana
            QBT_WEBUI_PORT: &port 80
            QBT_TORRENTING_PORT: &torrentPort 32388
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /api/v2/app/version
                  port: *port
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 1000Mi
      pod:
        annotations:
          reloader.stakater.com/auto: "true"
        securityContext:
          runAsUser: 1028
          runAsGroup: 100
          fsGroup: 100
          fsGroupChangePolicy: "OnRootMismatch"
  service:
    main:
      ports:
        http:
          port: *port
    bittorrent:
      type: LoadBalancer
      annotations:
        lbipam.cilium.io/ips: 10.10.0.245
      externalTrafficPolicy: Local
      ports:
        bt:
          port: *torrentPort
          protocol: TCP
  route:
    main:
      hostnames:
        - qbittorrent.mfin.app
      parentRefs:
        - name: envoy-internal
          namespace: envoy-gateway
      rules:
          - backendRefs:
              - identifier: main
                port: *port
  persistence:
    config:
      enabled: true
      existingClaim: qbittorrent
    data:
      enabled: true
      type: nfs
      server: synology.mfin.casa
      path: /volume1/data
      globalMounts:
        - path: /data
