app-template:
  controllers:
    main:
      replicas: 1
      type: statefulset
      containers:
        main:
          image:
            repository: ghcr.io/9001/copyparty-ac
            tag: 1.20.13@sha256:059c7e2c75a4d2402ccc23febc281b87dc80ec2ba2dcb23de1f666f0b33b9b74
          env:
            TZ: Europe/Ljubljana
            PRTY_NO_TLS: 1
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 1000Mi

      pod:
        securityContext:
          runAsUser: 1028
          runAsGroup: 100
          fsGroup: 100
          fsGroupChangePolicy: "OnRootMismatch"
  service:
    main:
      controller: main
      ports:
        http:
          port: 3923
  route:
    main:
      hostnames:
        - cp.mfin.app
      parentRefs:
        - name: envoy-internal
          namespace: envoy-gateway
  persistence:
    config:
      enabled: true
      existingClaim: copyparty
      globalMounts:
        - path: /cfg
    data:
      enabled: true
      server: synology.mfin.internal
      type: nfs
      path: /volume1/data
      globalMounts:
        - path: /w/data
