---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: audiomuse-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: audiomuse-secret
    template:
      data:
        NAVIDROME_USER: "{{ `{{ .navidromeUser }}` }}"
        NAVIDROME_PASSWORD: "{{ `{{ .navidromePassword }}` }}"
        POSTGRES_PASSWORD: "{{ `{{ .databasePassword }}` }}"
        OPENAI_API_KEY: "{{ `{{ .litellmApiKey }}` }}"
  data:
  - secretKey: navidromeUser
    remoteRef:
      key: "NAVIDROME_USER"
  - secretKey: navidromePassword
    remoteRef:
      key: "NAVIDROME_PASSWORD"
  - secretKey: databasePassword
    remoteRef:
      key: "AUDIOMUSE_DATABASE_PASSWORD"
  - secretKey: litellmApiKey
    remoteRef:
      key: "AUDIOMUSE_LITELLM_API_KEY"
