custom:
    target: ENC[AES256_GCM,data:aSIS5FxMiQqp+DQtfZVgbWCp6iirww==,iv:+NG3GJXg4KXFfVMasE2j2IrZ1TOiHSMKg0VGKUwyLyw=,tag:lGBKuCarTcJnOwWB78hHAg==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTk1UbHY3WUdCaE4yZ1lJ
            MHRlR2JoM01Hc2lDUWp3bExQeS9sLzRObG5NCmdjeHZORzQ5MGJxWno0SzBLUCtS
            UUYxL3RwZHVTRmtYYmNBejhLdXBtQVEKLS0tIDZSWjdpTnh0aXAyWTBkSm0zQURm
            STlqMnpPTkxYbXBZNENVU0tySkdCblEK/nITJNLLVfX47J3IyS69b5f91g0/aDVZ
            slUlx39gDFAE5o9mRkVW2sZybtP/yDDXyAyur52J2HaX8UEoS478Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T06:09:40Z"
    mac: ENC[AES256_GCM,data:8cfI7by7nYy4DjukGe4dwBkxg8IaAK7BWybP64Mp2faK89hRMXyqw+8evKbHNPKGvsPF1drrdA9PzqBkDD0AMswr/uPLYvQVcuL0RkZ2r5GYllaqZ+SkS//5xXnYZxl111EComFNRjjrFbsAJ2uWr2h2bCQ0dK5nwaMy3BsQqE8=,iv:vWpA7riatMu0chOJ1OrFgfWpBRmNZIWYpggowue+s9Q=,tag:0QnZxBGdEkMIczaFZ4QTSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
