apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |-
    ingress:
      - hostname: "*.mfin.app"
        service: "https://envoy-external.envoy-gateway.svc.cluster.local"
        originRequest:
          http2Origin: true
          originServerName: ext.mfin.app
      - hostname: "dnevna.com"
        service: "https://envoy-media.envoy-gateway.svc.cluster.local"
        originRequest:
          http2Origin: true
          originServerName: ext.dnevna.com
      - hostname: "*.dnevna.com"
        service: "https://envoy-media.envoy-gateway.svc.cluster.local"
        originRequest:
          http2Origin: true
          originServerName: ext.dnevna.com
      - service: http_status:404
