apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |-
    tunnel: "af89b57c-344b-40d2-972b-f03084dae14e"
    credentials-file: /etc/cloudflared/creds.json
    metrics: "0.0.0.0:8080"
    no-autoupdate: true
    originRequest:
      connectTimeout: 30s

    ingress:
      - hostname: "*.mfin.app"
        service: "https://envoy-external.envoy-gateway.svc.cluster.local"
        originRequest:
          originServerName: ext.mfin.app
      - hostname: "dnevna.com"
        service: "https://envoy-media.envoy-gateway.svc.cluster.local"
        originRequest:
          originServerName: ext.dnevna.com
      - hostname: "*.dnevna.com"
        service: "https://envoy-media.envoy-gateway.svc.cluster.local"
        originRequest:
          originServerName: ext.dnevna.com
      - service: http_status:404
