apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: cloudflared-secret
    template:
      data:
        creds.json: |
          {
            "AccountTag": "{{ `{{ .accountTag }}` }}",
            "TunnelSecret": "{{ `{{ .tunnelSecret }}` }}",
            "TunnelID": "af89b57c-344b-40d2-972b-f03084dae14e"
          }
  data:
  - secretKey: accountTag
    remoteRef:
      key: "CLOUDFLARED_ACCOUNT_TAG"
  - secretKey: tunnelSecret
    remoteRef:
      key: "CLOUDFLARED_TUNNEL_SECRET"
