apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: cloudflared-secret
    template:
      data:
        TUNNEL_TOKEN: "{{ `{{ .tunnelToken }}` }}"
  data:
  - secretKey: tunnelToken
    remoteRef:
      key: "CLOUDFLARED_TUNNEL_TOKEN"
