gateway-helm:
  global:
    imageRegistry: mirror.gcr.io
  config:
    envoyGateway:
      extensionApis:
        enableBackend: true
      provider:
        type: Kubernetes
        kubernetes:
          deploy:
            type: GatewayNamespace
