apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: vaultwarden-secret
    template:
      data:
        ADMIN_TOKEN: '{{ `{{ .adminToken }}` }}'
        SMTP_HOST: '{{ `{{ .smtpHost }}` }}'
        SMTP_FROM: '{{ `{{ .smtpFrom }}` }}'
        SMTP_USERNAME: '{{ `{{ .smtpUsername }}` }}'
        SMTP_PASSWORD: '{{ `{{ .smtpPassword }}` }}'
        SMTP_SECURITY: "starttls"
  data:
  - secretKey: adminToken
    remoteRef:
      key: "VAULTWARDEN_ADMIN_TOKEN"
  - secretKey: smtpHost
    remoteRef:
      key: "VAULTWARDEN_SMTP_HOST"
  - secretKey: smtpFrom
    remoteRef:
      key: "VAULTWARDEN_SMTP_FROM"
  - secretKey: smtpUsername
    remoteRef:
      key: "VAULTWARDEN_SMTP_USERNAME"
  - secretKey: smtpPassword
    remoteRef:
      key: "VAULTWARDEN_SMTP_PASSWORD"
