app-template:
  controllers:
    main:
      replicas: 1
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            repository: ghcr.io/autobrr/qui
            tag: v1.14.1@sha256:10b7945d4f0978f56a7cb939a011e1aeef3b8d500e825f409599ae754f95601b
          env:
            TZ: Europe/Ljubljana
            QUI__HOST: 0.0.0.0
            QUI__PORT: &port 80
            QUI__OIDC_ENABLED: true
            QUI__OIDC_DISABLE_BUILT_IN_LOGIN: true
            QUI__OIDC_CLIENT_ID: qui
            QUI__OIDC_REDIRECT_URL: https://qui.mfin.app/api/auth/oidc/callback
            QUI__OIDC_ISSUER: https://pocket.mfin.app
          envFrom:
            - secretRef:
                name: qui-secret
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ping
                  port: *port
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 1000Mi
      pod:
        annotations:
          reloader.stakater.com/auto: "true"
        securityContext:
          runAsUser: 1028
          runAsGroup: 100
          fsGroup: 100
          fsGroupChangePolicy: "OnRootMismatch"
  service:
    main:
      ports:
        http:
          port: *port
  route:
    main:
      hostnames:
        - qui.mfin.app
      parentRefs:
        - name: envoy-internal
          namespace: envoy-gateway
  persistence:
    config:
      enabled: true
      existingClaim: qui
    data:
      enabled: true
      type: nfs
      server: synology.mfin.internal
      path: /volume1/data
      globalMounts:
        - path: /data
