volsync:
    repository: ENC[AES256_GCM,data:aiHYNHwVy4E1Vcr5Owz/52FJKODm0C9r7I5juM9iOvwHRg44+9Euwvnv08g=,iv:SSS6qZpYZ6BwtgYQDc9Zokz6Ilyx4hQv+jWN1gx5Sk4=,tag:aojC8L2y5Ogu2I9UccL7OA==,type:str]
    password: ENC[AES256_GCM,data:+sBg+FR9RGCWntO8z7WZJ/8eEe5vqCjwim9LxtKodpo=,iv:ZI3/x/0sUPwwjWHMdzDbyd7GJGObmZ5MNt9L1JJ7yT4=,tag:egj6wV4gIQUDU8R8w3BGVQ==,type:str]
    accessKey: ENC[AES256_GCM,data:iypMyMOAfoxG5L977ZtOpg==,iv:siJMxQJ5gjfk54MKQi09LcQ395KxWl+19Mmdl45DFj8=,tag:n7p/1vaA0BK62UqY/6r6Fg==,type:str]
    secretKey: ENC[AES256_GCM,data:hxV35vLBuLggiiWWIkaqZ0wRbPLdvoEyX7HQrhBUu1g=,iv:UEnyJlON3Hp3b5SDAcI8Q4/W2r4B+aZ0XXj5lKpJz00=,tag:L64Vx3Rtb+nHpexEZzkbWw==,type:str]
minio:
    endpoint: ENC[AES256_GCM,data:H3ElodvMUSjyxIkAeKYZUJSC0A==,iv:g4dpRb9oZE0GhSjTNuivHfzyKEB2D9LcIi3t4P24sUE=,tag:buIhFxeWjWLCF78kyraPMQ==,type:str]
    bucket: ENC[AES256_GCM,data:dBg1J5F4qKu1QA==,iv:mRLYbvh3jX+3ldjeVb3KGuyrpxHpbnEzVFjzGTjtCYs=,tag:KtS1i/4R9iZ5WoiTcQpyQw==,type:str]
    accessKey: ENC[AES256_GCM,data:K0JLPVduzpSWlnfLvk+2GA==,iv:BaVkK96VTzbQWn8GtX3Hn2NUkzq8cEOEXdsWtjoYKYc=,tag:3OK9mQbZFFpvxZfQzpUcaQ==,type:str]
    secretKey: ENC[AES256_GCM,data:OJPdi4m9t9HXjHiXI08Dvjquz5Nyca2uuy4erw9ZX7c=,iv:eTGBWQWymsbi6jCDwNd5GWzFpKGONaYpfauLp3P9Jlc=,tag:kby0xnAQ7brmV/e3JVkEvQ==,type:str]
n8n:
    url: ENC[AES256_GCM,data:jzFWGlsKUY2qCfsE,iv:lkMu2uy8wrcluCkkIW270dWDCz8oXmu1W9ZlYrg1OW8=,tag:eUADsUCPojSG+omh46B1eg==,type:str]
    externalUrl: ENC[AES256_GCM,data:4/HfzxMO28mPcwi5UOhg1k0=,iv:yvD+Y8vJSymKs+PdS+ntbgPZ8WAaHV6a3kiNf7ERk9A=,tag:SoKXAixkvsNpbgOGVo9/+w==,type:str]
    ingressTarget: ENC[AES256_GCM,data:+QSfjAEsVhgYoio9,iv:YVOJmOMex33X3xDtPzhKu56io6LEcV7UJPpZBSfYWkg=,tag:h8czGYBc2SE8nbYMLKjutw==,type:str]
    encryptionKey: ENC[AES256_GCM,data:fj8zDprjhIJQNrsF+s36xn6w9A==,iv:pOE3K3mysqK88bG/1CupYxS/71JN5DhFFL/EFWUZ5MY=,tag:ZEnYNTxe7TI3DNcgPK56ZA==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:z6yw2GXxYIt8n1SJ6wd3w2T8zQ==,iv:Dw2RLJoTbSxYKNJtUlv4ELbLkP6yJszj/UgoEK507n4=,tag:SKTc2tH4pbGBUKg+HvDcUg==,type:str]
        user: ENC[AES256_GCM,data:v+f0N5bA1ejSwqMqEwtAoA==,iv:I8u4oQdp4J+1jfHTU64PU3cLjfgcLai0zERp70HqE58=,tag:DAnRWpM0opMMFqaF+8zuTA==,type:str]
        password: ENC[AES256_GCM,data:lMuIKX7x2j5m+74ybugbP8IYwXE=,iv:JrOnYr9Kugq39C+CIUqXD9aMp2fDP1zVIOCCCv5cna8=,tag:2Cn7exebsv9K4oALN7eBnw==,type:str]
        sender: ENC[AES256_GCM,data:eY/ArB+GZ/fyaS4m,iv:NFSlZdtB/5hSz8pc80SoKIFDHJBHWe15hKxhDesSwGY=,tag:MM8RegDxrT2U1LabtV88kw==,type:str]
    postgres:
        user: ENC[AES256_GCM,data:1VTQ,iv:VAQg25uAdoCd0Ub7JxnxVwUg59UXblYgHP2os8aqZNo=,tag:4ked5ZG0EOxmboULjxnd0A==,type:str]
        password: ENC[AES256_GCM,data:v5CrlirrUq+h141ei75eMnOgsBs=,iv:bOjpK1ePMNwHoYc63Ln2BTmfLiEeOsNjZvgMyOeafqM=,tag:QDnv72yaF/qZrQX57P8Y7A==,type:str]
        superPassword: ENC[AES256_GCM,data:Xg+08zTO674gFJm5l16QyYoR6B8=,iv:PeFp6q6Ixzz3r9MaAG1k4NB0G6IOtMQiDugJcOomRGY=,tag:NSgJem2m/b7SE0WmxNOpjw==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMWplT2sraWFleGNuOVcy
            Wi93eFE1OWJNOFcyWFd2bU8wWm5HcS9OdFVZCllFZWdSUDhUU3Znem9sMmc3andP
            MHdHcDJCVThQekh1SkdVTnVsOTNOQ1kKLS0tIFBYemNBaUpjUlhaeGNBYktSaHk4
            NzNPWDVaZitaVDZtWmh4VTJHNTFDVzAKaf+brySyIb0HCdquAGmj91fF+6TTfW/4
            epEn/pPydZKJ6PfZUcJF5oU3dE72r93XAz08EFiL0aPCM4Bx/tKeFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T06:08:06Z"
    mac: ENC[AES256_GCM,data:VqVMf8eoLqJqq6TqtwtYJowByjq89urH2pwvpuVxNvu4seLql5ZEJz7PG99RTGOioWp0nO5Qib6w0rCTrxhhNjs/q5aBetXxiw0DwzsiZAN0Cf5SzPhdp/D0U7DGY574M8BmIIdVQ3G22BAvE7JDRQLZxxb/JugbkzzbGg8PGkE=,iv:yi9ZpzLJ7HFxpJwtI6zmSxPkdeB8yKW32tj2rlyi3ZM=,tag:udLY3akuvDXcnH0q+wcYTA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
