app-template:
  controllers:
    main:
      annotations:
        reloader.stakater.com/auto: "true"
      type: statefulset
      replicas: 1
      initContainers:
        01-init-db:
          image:
            repository: ghcr.io/home-operations/postgres-init
            tag: 18.3@sha256:6fa1f331cddd2eb0b6afa7b8d3685c864127a81ab01c3d9400bc3ff5263a51cf
          envFrom:
            - secretRef:
                name: postgres
      containers:
        main:
          image:
            repository: ghcr.io/n8n-io/n8n
            tag: 2.11.1@sha256:39c634d65cf8830fec21ae7b242419e57737c2b1a1498b8b8c7578a585cf7ada
          command: ["n8n"]
          env:
            GENERIC_TIMEZONE: Europe/Ljubljana
            N8N_PORT: &port 80
            N8N_EMAIL_MODE: smtp
            N8N_METRICS: true
          envFrom:
            - secretRef:
                name: n8n
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /healthz
                  port: *port
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false
  service:
    main:
      ports:
        http:
          port: *port
  route:
    main:
      hostnames:
        - n8n.mfin.app
      parentRefs:
        - name: envoy-internal
          namespace: envoy-gateway
  persistence:
    data:
      existingClaim: n8n
      globalMounts:
        - path: /home/node/.n8n
