cloudflared:
    accountTag: ENC[AES256_GCM,data:EXghGielU3UgG+GsE7hAfrXcUtOI34+ZZ9VTMrzQCDo=,iv:dxQHEQrXZkwZLJiIKb+4NxhllmeMhbl46QutIQXxeuI=,tag:d/VtkwALh9OtBPWC9Rk05Q==,type:str]
    tunnelSecret: ENC[AES256_GCM,data:6CxxhQUoaF53bUo4iFLfshjxeqsTmWRcxBmBqayZhvDSxX7Jib7C458Z++Q=,iv:wqQn3q9AXCvto8hbmLLObncBc+xT+f/zjGpO/qGPpoM=,tag:Miz5WvYcgqCHMPQKI2qz2g==,type:str]
    tunnelId: ENC[AES256_GCM,data:s+2wX5e9ZxQtipAxxiRPci+cZQ/5fbdc/pCryRYdxx9u7V/X,iv:vUaA5cewRaLONqazgeZXOoC1bKR6cVxDlt87fcYpMzA=,tag:VtSQXU2Vad+WfjDp2YWapg==,type:str]
homelab:
    domain: ENC[AES256_GCM,data:9OUkVJpW3wM=,iv:OJIGyDTPgUoztnuxja/ooafiIvS1qrneCHa1sKC8gA4=,tag:OsuOgb/nturZSVjeaSIhMQ==,type:str]
    cname: ENC[AES256_GCM,data:dpzlctxfsZg2HR9zv4QWTNk=,iv:x1GQsHajine7fld3SfDxXuC3GBIF/MMscOGuPFP6RYw=,tag:EtB6KGL+02F+gkaM+F10CQ==,type:str]
    routes:
        - ENC[AES256_GCM,data:6J8M1tbkuSp3ITBvA14t,iv:OHJbboZ64uxAZKJS6hvpm4RkCEreVWY8B23Yw9eYdhQ=,tag:rNQa6ffFmWVvqj9grxv2UQ==,type:str]
        - ENC[AES256_GCM,data:boOFMQbV4pMNcmwr,iv:1TJrBKLDGe4UyrR1BhB1Ynf73agTdv6eIN/fAmqwsOQ=,tag:lpsZ1oYD8JU+wLbSWR/oAQ==,type:str]
        - ENC[AES256_GCM,data:NB2uIXrqlihToBthlBs=,iv:iZ1QcwCmvJZ4ra6+KLQNeXYM3pWPGeAMuEeBLyEaBVQ=,tag:HYQ+RT8RCynzPONbusdqBg==,type:str]
        - ENC[AES256_GCM,data:a5lcYk9Oc48Ya8ScLK4OSg==,iv:aYsc++Hahu9KStbuqkAob8c7xmO2I3lRLv2n4zuFRYg=,tag:k9B4CkMcgpxuWutoj/NVKA==,type:str]
media:
    domain: ENC[AES256_GCM,data:RAuVko6F3otv7A==,iv:ZbdSs/etC6BU0ecHLEt8spCuWtujQyvCdktfcTCL2SM=,tag:vOhOzdPRhjXvylz+L9+Ruw==,type:str]
    cname: ENC[AES256_GCM,data:w9ycw52dJE4UA9GvT1N/5u8enQ==,iv:8/Os3BWKf86qIrS9+7BABTCYYhu9BLLI9hOEqYDYMkY=,tag:xkZN0bmux6wyTU8lUQZqUw==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbHhzRHhHdHd1QlNVTUFi
            M0FTaXdsblNVWEpma0hmT2Vrd0JOOXh5MjBRCnhhUEEzRW4wRkVUdE54ZEp5UVBa
            NHErOUgweVBYM1ZtNnBDNFZndlk5MnMKLS0tIGxBaFJON2ZRaFFITnZud3hlQ3hi
            bzRKamZmU3pWT3hPbyttYWFBTEdwWTgKN3Wt78NBWDuWsqIsyWE1z6tTa0ktgE2z
            5w11MDGfUuaZYOJnsbQcd3icVnmvHC3vz9AfFAyUbf1aI+Sem9n5Qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T07:07:39Z"
    mac: ENC[AES256_GCM,data:52HovjcCHRYzqhQs3pvUhTg/JHgEUM5SsdJjiJdIqTGUsYuRcp2JsGKsT6UiVBmgNnt1rb8YsGrkXJGYTtmlcsSpW9EUq5b3sIi+uffkx36ps7/vF+p+U7wXafBA0t7HGYWs5TCXIIdj4nZr+gfSZRkkQ4Zo5Hn73FOqx5cRP2s=,iv:lSs9gyAIILmVBpfTC3SrIDur+JA/8hv/VbM1DR0Lt+g=,tag:RktDn2wlpBbZ0v9k/u5y/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
