cloudflared:
    accountTag: ENC[AES256_GCM,data:EXghGielU3UgG+GsE7hAfrXcUtOI34+ZZ9VTMrzQCDo=,iv:dxQHEQrXZkwZLJiIKb+4NxhllmeMhbl46QutIQXxeuI=,tag:d/VtkwALh9OtBPWC9Rk05Q==,type:str]
    tunnelSecret: ENC[AES256_GCM,data:6CxxhQUoaF53bUo4iFLfshjxeqsTmWRcxBmBqayZhvDSxX7Jib7C458Z++Q=,iv:wqQn3q9AXCvto8hbmLLObncBc+xT+f/zjGpO/qGPpoM=,tag:Miz5WvYcgqCHMPQKI2qz2g==,type:str]
    tunnelId: ENC[AES256_GCM,data:s+2wX5e9ZxQtipAxxiRPci+cZQ/5fbdc/pCryRYdxx9u7V/X,iv:vUaA5cewRaLONqazgeZXOoC1bKR6cVxDlt87fcYpMzA=,tag:VtSQXU2Vad+WfjDp2YWapg==,type:str]
homelab:
    domain: ENC[AES256_GCM,data:9OUkVJpW3wM=,iv:OJIGyDTPgUoztnuxja/ooafiIvS1qrneCHa1sKC8gA4=,tag:OsuOgb/nturZSVjeaSIhMQ==,type:str]
    cname: ENC[AES256_GCM,data:dpzlctxfsZg2HR9zv4QWTNk=,iv:x1GQsHajine7fld3SfDxXuC3GBIF/MMscOGuPFP6RYw=,tag:EtB6KGL+02F+gkaM+F10CQ==,type:str]
    routes:
        - ENC[AES256_GCM,data:6J8M1tbkuSp3ITBvA14t,iv:OHJbboZ64uxAZKJS6hvpm4RkCEreVWY8B23Yw9eYdhQ=,tag:rNQa6ffFmWVvqj9grxv2UQ==,type:str]
        - ENC[AES256_GCM,data:boOFMQbV4pMNcmwr,iv:1TJrBKLDGe4UyrR1BhB1Ynf73agTdv6eIN/fAmqwsOQ=,tag:lpsZ1oYD8JU+wLbSWR/oAQ==,type:str]
        - ENC[AES256_GCM,data:NB2uIXrqlihToBthlBs=,iv:iZ1QcwCmvJZ4ra6+KLQNeXYM3pWPGeAMuEeBLyEaBVQ=,tag:HYQ+RT8RCynzPONbusdqBg==,type:str]
        - ENC[AES256_GCM,data:a5lcYk9Oc48Ya8ScLK4OSg==,iv:aYsc++Hahu9KStbuqkAob8c7xmO2I3lRLv2n4zuFRYg=,tag:k9B4CkMcgpxuWutoj/NVKA==,type:str]
        - ENC[AES256_GCM,data:kLN0bA2DwFh9fOhCXm94,iv:+E2ngDb6spQKISZQW7LcXF8IU6L4HE8KT52YZXZiZvM=,tag:+FpoEaLo13qrgqYZEcPCuw==,type:str]
        - ENC[AES256_GCM,data:AJVk/odQx9Cog/6BNCDOE/Q=,iv:kwBGugqpqbdEgfrO1rwhKI3KeY1Rc/lpf7iUKA4wabg=,tag:4t7tRvYI7OkwNcYE+xM9qQ==,type:str]
        - ENC[AES256_GCM,data:yyMKfpg5dGDJ6qCDF6alvN7qTgThRoQ=,iv:4qvMotKeK+hNZ+wI9cUNmWSM6Fz705huwdSZuZJ/onE=,tag:u3yFolLvgRHqgcQV5EFATw==,type:str]
        - ENC[AES256_GCM,data:6bO9Nu1nIkNcYUDDuEI=,iv:PfM57PfnzIYkBKG5V1yXGP19rIOKFvkMT7nXAhd1lEs=,tag:VcvrxIZVyavkQ7ggm/95Mg==,type:str]
        - ENC[AES256_GCM,data:kq8o+BXKta4LIMPXnRIR,iv:vYIry++EZX0mIzSaKTEdFF0jmgMeZ1Cm639utWmEk1o=,tag:Jew4Vafw3+dHNi6a5q3+Jw==,type:str]
        - ENC[AES256_GCM,data:vMo7EyIrhAjGg80iCFHZdA==,iv:ToPmyk0vbU+1YPNsnmwJPfPNh5gEvXS3xO6m4C0y2WE=,tag:7JLxk/3V5U67JNSDyuD5mg==,type:str]
        - ENC[AES256_GCM,data:waFF1GOlTWdVkRO/Vw==,iv:4dtHlg05EC8Al6pnVEz7O7Mp/xgIYwOiM/GlMzHcd5A=,tag:bko2UjW/jAwEgphe+tFqyA==,type:str]
        - ENC[AES256_GCM,data:h4RkF3AwwIwdLqN1,iv:Hx3SdJDAcE4jY9LANopMWvG35/rOSDN6rzMNFUl1bPk=,tag:IKgLs/QfsFjbgOx/WHUOIQ==,type:str]
media:
    domain: ENC[AES256_GCM,data:RAuVko6F3otv7A==,iv:ZbdSs/etC6BU0ecHLEt8spCuWtujQyvCdktfcTCL2SM=,tag:vOhOzdPRhjXvylz+L9+Ruw==,type:str]
    cname: ENC[AES256_GCM,data:fu3isAP+cE0QJfyT3bY=,iv:7ccyWFikdKhgNRtNdVzsMHKE/t73q5ULWNI6/88XshA=,tag:PDeJwKG0W7qraeqi0sJJig==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbHhzRHhHdHd1QlNVTUFi
            M0FTaXdsblNVWEpma0hmT2Vrd0JOOXh5MjBRCnhhUEEzRW4wRkVUdE54ZEp5UVBa
            NHErOUgweVBYM1ZtNnBDNFZndlk5MnMKLS0tIGxBaFJON2ZRaFFITnZud3hlQ3hi
            bzRKamZmU3pWT3hPbyttYWFBTEdwWTgKN3Wt78NBWDuWsqIsyWE1z6tTa0ktgE2z
            5w11MDGfUuaZYOJnsbQcd3icVnmvHC3vz9AfFAyUbf1aI+Sem9n5Qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T12:13:23Z"
    mac: ENC[AES256_GCM,data:S1vDQguZ6rmgih8gTPhomg79/oB9JJu7bmbYyHretpphbGqPPdi6660GVRTdQkt1/9z+AdOvV+R3cKjvK2KUc1TDFFqtkjc/WMu+GU0QUQTvSq8kXMOcwKx3nLXy8ihm7GU6oTIaSPUlnvJ8shnPkPa7NW3aPAyYi3MqQjNo7FU=,iv:XDvEXBcnUpYAZfDEDtGXbxzZw7/RckkNQX/kqdkeuK8=,tag:h9b2Rz/syUGI96hRlS+qLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
