app-template:
  controllers:
    main:
      replicas: 1
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            repository: cloudflare/cloudflared
            tag: 2026.6.0
          env:
            TZ: "Europe/Ljubljana"
            NO_AUTOUPDATE: true
            TUNNEL_METRICS: 0.0.0.0:80
            TUNNEL_TRANSPORT_PROTOCOL: http2
          envFrom:
            - secretRef:
                name: cloudflared-secret
          args:
            - tunnel
            - run
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ready
                  port: &port 80
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 3
            readiness: *probes
      pod:
        priorityClassName: system-cluster-critical
  service:
    main:
      ports:
        http:
          port: *port
  serviceMonitor:
    main:
      enabled: true
      endpoints:
        - port: http
