app-template:
  enabled: false
  controllers:
    server:
      replicas: 1
      type: statefulset
      containers:
        server:
          image:
            repository: ghcr.io/neptunehub/audiomuse-ai
            tag: 0.9.2@sha256:c83a89422c8db308c7aeb3aceb86be2da256efe60c4554f02477bf6839b8fe09
          env:
            SERVICE_TYPE: flask
          envFrom:
            - configMapRef:
                name: audiomuse-config
            - secretRef:
                name: audiomuse-secret
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          resources:
            requests:
              cpu: 10m
              memory: 1Gi
            limits:
              memory: 6Gi
      pod:
        annotations:
          reloader.stakater.com/auto: "true"

    worker:
      replicas: 1
      containers:
        worker:
          image:
            repository: ghcr.io/neptunehub/audiomuse-ai
            tag: 0.9.2@sha256:c83a89422c8db308c7aeb3aceb86be2da256efe60c4554f02477bf6839b8fe09
          env:
            SERVICE_TYPE: worker
          envFrom:
            - configMapRef:
                name: audiomuse-config
            - secretRef:
                name: audiomuse-secret
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          resources:
            # claims:
            #   - name: gpu
            requests:
              cpu: 10m
              memory: 1Gi
            limits:
              memory: 2Gi
      pod:
        annotations:
          reloader.stakater.com/auto: "true"
        # resourceClaims:
        #   - name: gpu
        #     resourceClaimTemplateName: audiomuse-ai

  service:
    server:
      controller: server
      ports:
        http:
          port: 8000

  route:
    server:
      hostnames:
        - audiomuse.mfin.app
      parentRefs:
        - name: envoy-internal
          namespace: envoy-gateway
      rules:
        - backendRefs:
            - identifier: server
              port: 8000

  persistence:
    tmp:
      type: emptyDir
      globalMounts:
        - path: /app/temp_audio
